<a href="https://colab.research.google.com/github/mostefa-laoumir/TP-ML/blob/main/TP_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### DATA Preprocessing

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("/content/drive/MyDrive/training.csv")
target = data["FraudResult"]
y =data.iloc[:,-1]


data = data.drop(["TransactionId", "BatchId" ,"SubscriptionId" ,"AccountId","CustomerId","ProductCategory","CurrencyCode","ProviderId","ProductId","ChannelId","TransactionStartTime"], axis = 1)


In [ ]:
Xafterdrop = data.iloc[:,:].values
Xnew = data.iloc[:,:].values
y = target.iloc[:].values

from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
Xnew[:,0] = label.fit_transform(Xnew[:,0])
Xnew[:,1] = label.fit_transform(Xnew[:,1])
Xnew[:,-1] = label.fit_transform(Xnew[:,-1])
y = label.fit_transform(y)



In [ ]:

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
Xnew = scaler.fit_transform(Xnew)


from sklearn.decomposition import PCA
pca = PCA(2)
red_X = pca.fit_transform(Xnew)
ratio = pca.explained_variance_ratio_
y = label.fit_transform(y)

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(red_X,y , test_size = 0.2 , random_state = 0)


from sklearn.metrics import r2_score
from sklearn.metrics import confusion_matrix



### Models
## GaussianNB Model

In [39]:
from sklearn.naive_bayes import GaussianNB
print('Start.............')

classifier = GaussianNB()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
print('The score For Naive Bayes: ' , r2_score(y_test , y_pred))
print('The accuracy for NB is ', (y_pred == y_test).mean())
cm = confusion_matrix(y_test,y_pred)
print('Confusion Matrix is :\n', cm)
print('------------------------------------------------')

print('End.............')
      



Start.............
The score For Naive Bayes:  -0.08770402285953627
The accuracy for NB is  0.9980139026812314
Confusion Matrix is :
 [[19060    38]
 [    0    35]]
------------------------------------------------
End.............


## Logistic Regression Model

In [43]:
print('Start.............')

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

print('The score For Linear Regression: ' , r2_score(y_test , y_pred))
print('The accuracy for Linear Regression is ', (y_pred == y_test).mean())
cm = confusion_matrix(y_test,y_pred)
print('Confusion Matrix is :\n', cm)
print('------------------------------------------------')

print('End.............')

Start.............
The score For Linear Regression:  1.0
The accuracy for Linear Regression is  1.0
Confusion Matrix is :
 [[19098     0]
 [    0    35]]
------------------------------------------------
End.............


##Support Vector Machine (SVM)

In [42]:
print('Start.............')

from sklearn import svm
classifier = svm.SVC()
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

print('The score For SVM: ' , r2_score(y_test , y_pred))
print('The accuracy for SVM is ', (y_pred == y_test).mean())
cm = confusion_matrix(y_test,y_pred)
print('Confusion Matrix is :\n', cm)
print('------------------------------------------------')

print('End.............')

Start.............
The score For SVM:  0.9427524198494981
The accuracy for SVM is  0.99989546856217
Confusion Matrix is :
 [[19096     2]
 [    0    35]]
------------------------------------------------
End.............


###Boosting

In [41]:
from sklearn.ensemble import AdaBoostClassifier
print('Start.............')

classifier = AdaBoostClassifier(n_estimators=100,learning_rate=1,random_state=123)
classifier.fitted = classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

print('The score For Boosting: ' , r2_score(y_test , y_pred))
print('The accuracy for Boosting is ', (y_pred == y_test).mean())
cm = confusion_matrix(y_test,y_pred)
print('Confusion Matrix is :\n', cm)
print('------------------------------------------------')

print('End.............')

Start.............
The score For Boosting:  1.0
The accuracy for Boosting is  1.0
Confusion Matrix is :
 [[19098     0]
 [    0    35]]
------------------------------------------------
End.............


# KNN (K-nearest neighbor)

In [40]:
from sklearn.neighbors import KNeighborsClassifier


print('Start.............')

classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)
print('The score For KNN: with number of neighbors is 3 : ' , r2_score(y_test , y_pred))
print('The accuracy for KNN is : with number of neighbors is 3 :  ', (y_pred == y_test).mean())
cm = confusion_matrix(y_test,y_pred)
print('Confusion Matrix is :\n', cm)
print('------------------------------------------------')

print('End.............')

Start.............
The score For KNN: with number of neighbors is 3 :  1.0
The accuracy for KNN is : with number of neighbors is 3 :   1.0
Confusion Matrix is :
 [[19098     0]
 [    0    35]]
------------------------------------------------
End.............
